### ISSUE TITLE
ycecream printing in ASCII instead of Unicode?

### ISSUE THREAD

**Issue by robinvandernoord** [salabim/ycecream#11]
When y-ing a string containing the character "ö", ycecream throws the following exception:

```
Traceback (most recent call last):
  File "/p4w/apps/front_end/graphql_support.py", line 754, in user
    y(response)
  File "/usr/local/lib/python3.8/dist-packages/ycecream/ycecream.py", line 607, in __call__
    this.do_output(out)
  File "/usr/local/lib/python3.8/dist-packages/ycecream/ycecream.py", line 740, in do_output
    print(s, file=sys.stderr)
UnicodeEncodeError: 'ascii' codec can't encode character '\xf6' in position 729: ordinal not in range(128)
```

Why is ycecream even trying to use the ascii codec? Shouldn't it be unicode by default?
The locale is set to UTF-8 correctly. Is there some other settings that can be changed somewhere?

**Comment by robinvandernoord** [comment]
Something appeared to be off in the environment. It was using `ANSI_X3.4-1968` encoding.
```python
sys.stdout.reconfigure(encoding="utf-8")
```
seems to have fixed the issue
